### ISSUE TITLE
Correct Sponsor Levels Vertical Display Order

### ISSUE THREAD

**Issue by nvisionative** [DNNAssociation/DnnSummit2019.Mobile#102]
## Description of bug
Need to correct the vertical display order for all sponsor levels.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Info'
2. Click on 'Sponsors'
3. See **Title** sponsor below **Platinum** sponsor

## Current result
**Title** sponsor is currently below **Platinum** sponsor.

## Expected result
**Title** sponsor should be above **Platinum** sponsor.

## Screenshots
![3d6b338e-f29d-4484-b18b-c043e03359cb](https://user-images.githubusercontent.com/4568451/52510739-363f8a00-2bcb-11e9-985b-488c9afcebab.png)

## Error log
n/a

## Additional context
n/a

## Affected version
* [x] 1.0.0

## Affected device
* [x] Android
* [ ] iOS

**Comment by ahoefling** [comment]
Thanks for reporting this

**Comment by ahoefling** [comment]
fixes: #102
