### ISSUE TITLE
RFC: Offline/Online Web Request Rules

### ISSUE THREAD

**Issue by ahoefling** [DNNAssociation/DnnSummit2019.Mobile#34]
## Summary
A good mobile app should not prevent the user from using all of the functionality during online vs offline mode. Especially an app like this that only reads data as there is no writing of data.

## Extended description
I am looking for a business rules discussion so the appropriate rules can be implemented.

## Current Implementation
#31 is the MVP of offline sync, the current business rules and use cases are outlined below:

### Web Requests
Due to uncertain network connections in the mobile ecosystem it is best to limit your network requests. The MVP implementation in #31 does just that. It attempts to download all the content and caches it in a local database. Every screen that is loaded uses the locally cached data.

### First Load
When the app first loads all the content is downloaded. All network requests from then on out use the cached data.

### Any App Load
During the App load phase the app checks for an active internet connection. If there is no internet connection it will open the app and used the cached data.

If there is internet connection the data will refresh.

### Force Download
If the user would like to do a force download there is a button in the Info/About page that allows them to clear their cache and download the data fresh

## Questions

* What should we do if the user can't download the data for whatever reason? Maybe we have a 404 page saying it was unable to download and they can try again
* When should we expire the cache? In the event a user never shuts down their app the data may never reload. If we set an expiration on the cache we can force it to reload at any point during usage of the app

**Comment by ahoefling** [comment]
I am looking for an open discussion and feedback on how people think offline mode should work for this app.

**Comment by ahoefling** [comment]
I added #35 which is going to cover the case if the user opens the app and loses internet. Which would mean they aren't able to download any of the content. This will create a No Data or 404 screen that will tell the user they couldn't download the data for whatever reason and they can try again.

This is important to prevent an App crash

**Comment by mitchelsellers** [comment]
I think the big thing will be a notification to the user that application content is current as of __.

For example

"Unable to  update content, information current as of xx/xx/xxxx, Contact event staff for any changes"

That is about it.  Manual refresh is great as well

**Comment by CBPSC** [comment]
I agree with Mitchel on this one!

**Comment by ahoefling** [comment]
I think what we will do is update the loading screen to notify the user with the message:
"Unable to update content, information current as of xx/xx/xxxx, Contact event staff for any change".

At the bottom of each page there will be a small note of when the data was last downloaded.

### Created the following Issues:

* #42 (offline mode splash screen)
* #43 Data Retrieved Message

**Comment by ahoefling** [comment]
I think we have good direction on this item. I am going to close it out
